analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0.7416756
  lightness: 0.6589689
  brandColors:
    - '#010101'
    - '#645430'
    - '#A49965'
    - '#C7BB88'
    - '#797971'
  rhythmicContrast: 0.3711063
typography_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.04672394
favicon: null
name: Criminal Defense
